#!/bin/sh
set -e

. /usr/share/debconf/confmodule

db_version 2.0

db_input medium tacacsrs-agentd/config-source || true
db_go || true

db_get tacacsrs-agentd/config-source || true
if [ "$RET" = "sonic-configdb" ]; then
    db_set tacacsrs-agentd/install-sonic-service true || true
    db_fset tacacsrs-agentd/install-sonic-service seen false || true
    db_input medium tacacsrs-agentd/install-sonic-service || true
    db_go || true
else
    db_set tacacsrs-agentd/install-sonic-service false || true
    db_fset tacacsrs-agentd/install-sonic-service seen true || true
fi

exit 0