[package]
name = "tacacsrs-flows"
version = "0.0.0-dev"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "TACACS+ protocol flow implementations decoupled from transport/session internals"

[dependencies]
anyhow = { version = "1.0.102", features = ["backtrace"] }
async-trait = "0.1.89"
log = "0.4.29"
tacacsrs-flow-abstractions = { path = "../tacacsrs_flow_abstractions" }
tacacsrs-messages = { path = "../tacacsrs_messages" }

[dev-dependencies]
tacacsrs-networking = { path = "../tacacsrs_networking" }
tokio = { version = "1.52.3", features = ["full"] }

[lints]
workspace = true
