[[secret]]
module = "ietf-system-tacacs-plus"
leaf = "shared-secret"
kind = "string"
expected_matches = 1

[[secret]]
module = "ietf-crypto-types"
leaf = "cleartext-symmetric-key"
kind = "binary"
expected_matches = 1

[[secret]]
module = "ietf-crypto-types"
leaf = "cleartext-private-key"
kind = "binary"
expected_matches = 1