[package]
name = "tacacs-client-service"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Central TACACS+ client service for local consumers"

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
clap = { version = "4.5.57", features = ["derive"] }
tacacsrs-client-service-client = { path = "../../libraries/tacacsrs_client_service_client" }
tacacsrs-client-service = { path = "../../libraries/tacacsrs_client_service" }
tokio = { version = "1.49.0", features = ["full"] }

[features]
default = []
psk = ["tacacsrs-client-service/psk"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
