[package]
name = "tacacsrs-agent"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Reusable central TACACS+ client service components and IPC protocol"
readme = "README.md"

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
async-trait = "0.1.89"
log = "0.4.29"
tacacsrs-agent-client = { path = "../tacacsrs_agent_client" }
tacacsrs-messages = { path = "../tacacsrs_messages" }
tacacsrs-networking = { path = "../tacacsrs_networking" }
tokio = { version = "1.49.0", features = ["full"] }
tokio-stream = { version = "0.1.18", features = ["net"] }
tonic = "0.14.5"

[features]
default = []
psk = ["tacacsrs-networking/psk"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
