name: Build Debian Package
description: Build Debian package and debug symbol package with cargo-deb

inputs:
  package-name:
    description: 'Cargo package name to pass to cargo-deb'
    required: true

runs:
  using: composite
  steps:
    - name: Generate Debian package
      shell: bash
      run: cargo deb --package ${{ inputs.package-name }} --no-build --dbgsym
