#![doc = include_str!("../README.md")]
#![allow(clippy::doc_markdown)]

use std::pin::Pin;
use std::sync::Arc;

use async_trait::async_trait;
use futures_core::Stream;
use tacacsrs_config::TacacsPlus;
use tokio::sync::watch;
use tokio_stream::wrappers::WatchStream;
use tokio_stream::StreamExt;

/// Description of how the configuration changed between two snapshots.
///
/// Each [`ConfigChange`] carries the complete new [`TacacsPlus`] snapshot.
/// Consumers should treat that snapshot as authoritative and use this delta as
/// a decision aid: apply an incremental update when the delta is simple enough,
/// or rebuild from the full snapshot when that is safer.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ConfigDelta {
    /// Server names present in the new snapshot but not in the previous one.
    pub added_servers: Vec<String>,
    /// Server names present in the previous snapshot but not in the new one.
    pub removed_servers: Vec<String>,
    /// Server names whose definitions changed between snapshots.
    pub modified_servers: Vec<String>,
    /// Set when something other than the per-server table changed (for example
    /// shared `client-credentials` / `server-credentials` bundles). When
    /// `true`, consumers should treat the entire configuration as potentially
    /// changed even if the server-level deltas are empty.
    pub root_metadata_changed: bool,
}

impl ConfigDelta {
    /// Returns `true` if no server-level or root-level changes were detected.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.added_servers.is_empty()
            && self.removed_servers.is_empty()
            && self.modified_servers.is_empty()
            && !self.root_metadata_changed
    }

    /// Compute the delta between the previous snapshot and the new snapshot.
    ///
    /// "Modified" is determined by structural inequality of the matching
    /// [`tacacsrs_config::TacacsPlusServer`]; backends that wish to emit a
    /// finer-grained change (for example a passkey rotation only) may
    /// construct a [`ConfigDelta`] directly instead of calling this helper.
    #[must_use]
    pub fn diff(previous: Option<&TacacsPlus>, new: &TacacsPlus) -> Self {
        let Some(previous) = previous else {
            return Self {
                added_servers: new.server.iter().map(|s| s.name.clone()).collect(),
                removed_servers: Vec::new(),
                modified_servers: Vec::new(),
                root_metadata_changed: !new.client_credentials.is_empty()
                    || !new.server_credentials.is_empty(),
            };
        };

        let mut added = Vec::new();
        let mut modified = Vec::new();
        for server in &new.server {
            match previous.server.iter().find(|s| s.name == server.name) {
                None => added.push(server.name.clone()),
                Some(prev) if !structurally_equal(prev, server) => {
                    modified.push(server.name.clone());
                }
                _ => {}
            }
        }

        let removed = previous
            .server
            .iter()
            .filter(|prev| !new.server.iter().any(|s| s.name == prev.name))
            .map(|s| s.name.clone())
            .collect::<Vec<_>>();

        let root_metadata_changed =
            !slice_structurally_equal(&previous.client_credentials, &new.client_credentials)
                || !slice_structurally_equal(&previous.server_credentials, &new.server_credentials);

        Self {
            added_servers: added,
            removed_servers: removed,
            modified_servers: modified,
            root_metadata_changed,
        }
    }
}

/// Compare two values by their canonical JSON representation.
///
/// The YANG-generated types in [`tacacsrs_config`] do not derive `PartialEq`
/// because they are regenerated by an out-of-tree tool. Comparing through
/// `serde_json::Value` keeps the diff implementation forward-compatible with
/// schema additions: any field that round-trips through `serde` participates
/// in equality automatically, and serialization failures fall back to
/// "treat as changed" so we never silently miss an update.
fn structurally_equal<T: serde::Serialize>(a: &T, b: &T) -> bool {
    match (serde_json::to_value(a), serde_json::to_value(b)) {
        (Ok(a), Ok(b)) => a == b,
        _ => false,
    }
}

fn slice_structurally_equal<T: serde::Serialize>(a: &[T], b: &[T]) -> bool {
    a.len() == b.len()
        && a.iter()
            .zip(b.iter())
            .all(|(x, y)| structurally_equal(x, y))
}

/// Event broadcast by a [`ConfigDatastore`] when the upstream configuration
/// changes.
///
/// Each event carries the full validated [`TacacsPlus`] snapshot so consumers
/// receive monitor-style notifications: the payload is the latest complete
/// configuration, and `delta` is a decision aid for incremental handling.
#[derive(Debug, Clone)]
pub struct ConfigChange {
    /// The new validated configuration.
    pub config: Arc<TacacsPlus>,
    /// What the backend believes changed compared to the previous snapshot.
    pub delta: ConfigDelta,
}

/// Typed event emitted by a datastore change subscription.
#[derive(Debug, Clone)]
pub enum ConfigChangeEvent {
    /// A complete validated candidate snapshot is available.
    Changed(ConfigChange),
    /// The datastore observed a change but rejected the resulting candidate.
    ///
    /// Backends log their detailed error locally. The event intentionally
    /// carries no error text or configuration value so health consumers cannot
    /// expose addresses, credential references, or secrets.
    CandidateRejected,
    /// A validated host-binding setting changed but cannot be applied live.
    ///
    /// The current bound resources remain active until process restart. No
    /// configuration values are included in this event.
    RestartRequired {
        /// Whether the current validated settings differ from bound resources.
        required: bool,
    },
}

/// Stream of [`ConfigChangeEvent`] values returned by [`ConfigDatastore::subscribe`].
pub type ConfigChangeStream = Pin<Box<dyn Stream<Item = ConfigChangeEvent> + Send + 'static>>;

/// Behavior the runtime applies when the initial datastore load fails.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum InitialLoadPolicy {
    /// Return the load error to the operator and stop startup.
    FailFast,
    /// Retry until a valid snapshot is available or shutdown is requested.
    RetryUntilAvailable,
}

/// Change-notification guarantees provided by a datastore instance.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum ChangeNotificationMode {
    /// The datastore is immutable for the lifetime of the process.
    None,
    /// The datastore maintains a continuous subscription that must be restored
    /// if setup fails or its stream ends.
    Continuous,
}

/// Runtime behavior declared by a [`ConfigDatastore`] instance.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub struct DatastoreRuntimePolicy {
    /// Initial-load failure behavior.
    pub initial_load: InitialLoadPolicy,
    /// Change-notification behavior.
    pub change_notifications: ChangeNotificationMode,
}

impl DatastoreRuntimePolicy {
    /// Creates a datastore runtime policy.
    #[must_use]
    pub const fn new(
        initial_load: InitialLoadPolicy,
        change_notifications: ChangeNotificationMode,
    ) -> Self {
        Self {
            initial_load,
            change_notifications,
        }
    }
}

/// Source of TACACS+ configuration for the agent runtime.
///
/// Implementations supply the initial configuration via [`load`] and an
/// asynchronous stream of subsequent updates via [`subscribe`]. Both calls
/// return validated configurations: backends are responsible for translating
/// vendor-specific formats into the YANG-aligned [`TacacsPlus`] structure and
/// for failing the corresponding call when validation rejects the input.
///
/// [`load`]: ConfigDatastore::load
/// [`subscribe`]: ConfigDatastore::subscribe
#[async_trait]
pub trait ConfigDatastore: Send + Sync + 'static {
    /// Declares how the runtime should supervise this datastore instance.
    ///
    /// This is an instance-level contract because a file-backed datastore may
    /// be immutable when no referenced paths exist and continuously watched
    /// when its effective configuration depends on files.
    fn runtime_policy(&self) -> DatastoreRuntimePolicy;

    /// Load the current configuration snapshot.
    ///
    /// Called once at startup and may be called again by callers that wish to
    /// re-read the configuration without subscribing to change events.
    ///
    /// # Errors
    ///
    /// Returns an error if the backing store cannot be reached or if the
    /// retrieved configuration fails validation.
    async fn load(&self) -> anyhow::Result<TacacsPlus>;

    /// Subscribe to configuration change events.
    ///
    /// The returned stream emits a [`ConfigChange`] each time the backend
    /// observes a relevant change in the underlying store. Every event carries
    /// the complete latest snapshot; callers may use the delta to choose an
    /// incremental update path but should fall back to rebuilding from the
    /// snapshot whenever the delta is not sufficient. Backends that cannot
    /// deliver change notifications return an empty stream.
    ///
    /// # Errors
    ///
    /// Returns an error if the subscription cannot be established (for
    /// example, the backing store is unreachable). Implementations that do
    /// not support change notifications return an empty stream rather than
    /// failing.
    async fn subscribe(&self) -> anyhow::Result<ConfigChangeStream>;

    /// Human-readable label describing the datastore implementation.
    ///
    /// Used in operator logs to disambiguate which datastore the agent is
    /// running against (for example, `"static"`, `"sonic-configdb"`).
    fn label(&self) -> &'static str;
}

/// In-memory [`ConfigDatastore`] for CLI/file/test workflows.
///
/// `StaticDatastore` holds a single `TacacsPlus` snapshot for the lifetime of
/// the process. [`subscribe`](ConfigDatastore::subscribe) returns an empty
/// stream because the configuration cannot change.
#[derive(Debug, Clone)]
pub struct StaticDatastore {
    config: Arc<TacacsPlus>,
    label: &'static str,
}

impl StaticDatastore {
    /// Create a new static datastore backed by an already-validated config.
    #[must_use]
    pub fn new(config: TacacsPlus) -> Self {
        Self::with_label(config, "static")
    }

    /// Create a new static datastore with a caller-supplied label.
    ///
    /// The label is reported by [`ConfigDatastore::label`] and intended for
    /// operator logs (for example `"file"` or `"cli"`).
    #[must_use]
    pub fn with_label(config: TacacsPlus, label: &'static str) -> Self {
        Self {
            config: Arc::new(config),
            label,
        }
    }
}

#[async_trait]
impl ConfigDatastore for StaticDatastore {
    fn runtime_policy(&self) -> DatastoreRuntimePolicy {
        DatastoreRuntimePolicy::new(InitialLoadPolicy::FailFast, ChangeNotificationMode::None)
    }

    async fn load(&self) -> anyhow::Result<TacacsPlus> {
        Ok((*self.config).clone())
    }

    async fn subscribe(&self) -> anyhow::Result<ConfigChangeStream> {
        Ok(Box::pin(tokio_stream::empty()))
    }

    fn label(&self) -> &'static str {
        self.label
    }
}

/// Helper for backends that publish updates through a `tokio::sync::watch`
/// channel.
///
/// The first value sent on the channel is treated as the initial snapshot and
/// is not republished as a change. Subsequent updates are emitted as
/// [`ConfigChange`] values with deltas computed against the previously
/// observed snapshot.
#[must_use]
pub fn watch_to_change_stream(
    receiver: watch::Receiver<Option<Arc<TacacsPlus>>>,
) -> ConfigChangeStream {
    let mut previous: Option<Arc<TacacsPlus>> = receiver.borrow().clone();
    let stream = WatchStream::from_changes(receiver).filter_map(move |snapshot| {
        let snapshot = snapshot?;
        let delta = ConfigDelta::diff(previous.as_deref(), &snapshot);
        let change = ConfigChange {
            config: Arc::clone(&snapshot),
            delta,
        };
        previous = Some(snapshot);
        Some(ConfigChangeEvent::Changed(change))
    });
    Box::pin(stream)
}

#[cfg(test)]
mod tests {
    use std::time::Duration;

    use super::*;
    use tacacsrs_config::{TacacsPlusBuilder, TacacsPlusServerBuilder, TacacsPlusServerType};

    fn sample_config(addr: &str) -> TacacsPlus {
        TacacsPlusBuilder::new()
            .with_server_builder(
                TacacsPlusServerBuilder::new("primary", TacacsPlusServerType::all(), addr, 49)
                    .with_shared_secret("topsecret"),
            )
            .build()
            .expect("sample config should validate")
    }

    #[tokio::test]
    async fn static_datastore_returns_config_and_empty_stream() {
        let config = sample_config("192.0.2.1");
        let store = StaticDatastore::new(config.clone());
        let loaded = store.load().await.expect("load should succeed");
        assert_eq!(loaded.server.len(), 1);
        assert_eq!(store.label(), "static");
        assert_eq!(
            store.runtime_policy(),
            DatastoreRuntimePolicy::new(InitialLoadPolicy::FailFast, ChangeNotificationMode::None,)
        );

        let mut stream = store.subscribe().await.expect("subscribe should succeed");
        assert!(stream.next().await.is_none(), "static stream should be empty");
    }

    #[test]
    fn delta_detects_added_modified_and_removed_servers() {
        let mut previous = sample_config("192.0.2.1");
        previous.server.push(
            TacacsPlusServerBuilder::new("secondary", TacacsPlusServerType::all(), "192.0.2.2", 49)
                .with_shared_secret("topsecret")
                .build(),
        );

        let mut new = sample_config("192.0.2.1");
        // Modify primary
        new.server[0].timeout = 10;
        // Add a tertiary server
        new.server.push(
            TacacsPlusServerBuilder::new("tertiary", TacacsPlusServerType::all(), "192.0.2.3", 49)
                .with_shared_secret("topsecret")
                .build(),
        );
        // Removed: secondary

        let delta = ConfigDelta::diff(Some(&previous), &new);
        assert_eq!(delta.added_servers, vec!["tertiary"]);
        assert_eq!(delta.removed_servers, vec!["secondary"]);
        assert_eq!(delta.modified_servers, vec!["primary"]);
        assert!(!delta.root_metadata_changed);
        assert!(!delta.is_empty());
    }

    #[test]
    fn delta_against_no_previous_marks_all_added() {
        let new = sample_config("192.0.2.1");
        let delta = ConfigDelta::diff(None, &new);
        assert_eq!(delta.added_servers, vec!["primary"]);
        assert!(delta.removed_servers.is_empty());
        assert!(delta.modified_servers.is_empty());
        assert!(!delta.root_metadata_changed);
    }

    #[tokio::test]
    async fn watch_stream_emits_subsequent_updates_only() {
        let initial = Arc::new(sample_config("192.0.2.1"));
        let (tx, rx) = watch::channel(Some(Arc::clone(&initial)));
        let mut stream = watch_to_change_stream(rx);

        // No update yet — initial value is the baseline, not a change.
        assert!(tokio::time::timeout(Duration::from_millis(25), stream.next())
            .await
            .is_err());

        let mut updated = sample_config("192.0.2.1");
        updated.server[0].timeout = 7;
        let updated_arc = Arc::new(updated);
        tx.send(Some(Arc::clone(&updated_arc)))
            .expect("send update");

        let ConfigChangeEvent::Changed(change) =
            stream.next().await.expect("should receive change")
        else {
            panic!("expected a changed event");
        };
        assert_eq!(change.delta.modified_servers, vec!["primary"]);
        assert_eq!(change.config.server[0].timeout, 7);
    }

    #[tokio::test]
    async fn watch_stream_keeps_update_sent_before_first_poll() {
        let initial = Arc::new(sample_config("192.0.2.1"));
        let (tx, rx) = watch::channel(Some(Arc::clone(&initial)));
        let mut stream = watch_to_change_stream(rx);

        let mut updated = sample_config("192.0.2.1");
        updated.server[0].timeout = 9;
        tx.send(Some(Arc::new(updated))).expect("send update");

        let ConfigChangeEvent::Changed(change) = stream
            .next()
            .await
            .expect("should receive first real update")
        else {
            panic!("expected a changed event");
        };
        assert_eq!(change.delta.modified_servers, vec!["primary"]);
        assert_eq!(change.config.server[0].timeout, 9);
    }
}
