//! Generated protobuf/gRPC types for the local IPC transport.
//!
//! The `.proto` file is checked into the repository as the source of truth for
//! the on-the-wire IPC contract:
//!
//! [`proto/tacacsrs_agent.proto`](https://github.com/AuthScaffold/tacacs-rs/blob/main/libraries/tacacsrs_agent_client/proto/tacacsrs_agent.proto)
//!
//! The generated Rust bindings are included at build time via
//! [`tonic::include_proto!`] so the rest of the crate can convert between
//! domain types and the transport schema without hand-maintaining
//! serialization code.
//!
//! # Generated contents
//!
//! The protobuf schema produces the following Rust types:
//!
//! | Proto type | Rust type |
//! |------------|-----------|
//! | `AccountingRequest` | request message |
//! | `AccountingResponse` | response message |
//! | `AccountingReply` | oneof reply envelope |
//! | `ServiceError` | structured error |
//! | `AccountingStatus` | status enum |
//! | `TacacsAgent` | server/client trait + stubs |
//!
//! > **Note:** All clippy lints are suppressed in this module because the code
//! > is machine-generated by `tonic-prost-build`.

#![allow(clippy::all, clippy::pedantic)]

tonic::include_proto!("tacacsrs.agent.v1");
