#![doc = include_str!("../README.md")]

/// Local gRPC client helpers for talking to the central TACACS+ service.
///
/// The [`ServiceClient`] type is the main entry point. Callers construct it
/// with [`ServiceClient::connect`], passing an [`IpcEndpoint`], and then issue
/// unary accounting or authorization RPCs over the persistent gRPC channel. Each call converts
/// between domain types and protobuf and returns a typed result.
pub mod client;

mod endpoint;

/// Stable names used by standard gRPC health checks.
pub mod health;

/// Generated protobuf/gRPC types for the local IPC transport.
///
/// The `.proto` file
/// ([`proto/tacacsrs_agent.proto`](https://github.com/AuthScaffold/tacacs-rs/blob/main/libraries/tacacsrs_agent_client/proto/tacacsrs_agent.proto))
/// is checked into the repository as the source of truth for the on-the-wire
/// IPC contract. The generated Rust bindings are included at build time so
/// the rest of the crate can convert between domain types and the transport
/// schema without hand-maintaining serialization code.
///
/// > **Note:** All clippy lints are suppressed in this module because the code
/// > is machine-generated by `tonic-prost-build`.
pub mod ipc;

/// Domain-level request and response types for the local TACACS+ client API.
///
/// The local IPC transport is defined in protobuf and served over gRPC, but
/// the rest of the crate works with these operation-centric Rust types so
/// callers do not have to depend on generated transport code directly.
pub mod protocol;

pub use client::ServiceClient;
pub use endpoint::IpcEndpoint;
pub use health::HealthClient;
pub use protocol::{
    AccountingOperation, AccountingOperationResponse, AccountingResponseStatus, AuthorizationArg,
    AuthorizationKey, AuthorizationOperation, AuthorizationOperationResponse,
    AuthorizationRequestBuilder, AuthorizationResponseStatus, ServiceError,
};
