[package]
name = "tacacsrs-messages"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.89", features = ["backtrace"] }
bitflags = "2.6.0"
byteorder = "1.5.0"
num_enum = "0.7.3"
