[package]
name = "tacacsrs-messages"
version = "0.0.0-dev"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "TACACS+ protocol message types and serialization"

[dependencies]
anyhow = { version = "1.0.102", features = ["backtrace"] }
bitflags = "2.11.1"
byteorder = "1.5.0"
md-5 = "0.11.0"
num_enum = "0.7.6"
zeroize = "1.9.0"

[lints]
workspace = true
