syntax = "proto3";

package tacacsrs.agent.mock.v1;

service TacacsAgentMockController {
  rpc LoadPolicy(LoadPolicyRequest) returns (LoadPolicyReply);
  rpc ResetState(ResetStateRequest) returns (ResetStateReply);
  rpc GetCapturedRequests(GetCapturedRequestsRequest) returns (GetCapturedRequestsReply);
  rpc Shutdown(ShutdownRequest) returns (ShutdownReply);
}

message LoadPolicyRequest {
  // The emulator evaluates this Rego policy for each IPC request.
  string policy_rego = 1;
  // Fixed policy data in a JSON object. An empty string means that there is no data.
  string data_json = 2;
}

message LoadPolicyReply {}

message ResetStateRequest {}

message ResetStateReply {}

message GetCapturedRequestsRequest {}

message GetCapturedRequestsReply {
  repeated CapturedIpcRequest requests = 1;
}

message CapturedIpcRequest {
  string rpc = 1;
  string request_json = 2;
}

message ShutdownRequest {}

message ShutdownReply {}
