/**
 * TACACS-rs FFI Bindings
 * 
 * C/C++ bindings for the TACACS+ protocol implementation.
 * 
 * This header provides a Foreign Function Interface (FFI) to use
 * the TACACS-rs library from C and C++ applications.
 * 
 * @file tacacs.h
 * @version 0.1.1
 * @license MIT
 */


#ifndef TACACS_H
#define TACACS_H

/* Warning: This file is automatically generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * TACACS+ flags
 */
#define tacacs_TACACS_FLAG_UNENCRYPTED 1

#define tacacs_TACACS_FLAG_SINGLE_CONNECTION 4

/**
 * TACACS+ major version enumeration
 */
typedef enum tacacs_CTacacsMajorVersion {
    /**
     * TACACS+ Major Version 1 (0xC)
     */
    TACACS_C_TACACS_MAJOR_VERSION_TACACS_PLUS_MAJOR1 = 12,
} tacacs_CTacacsMajorVersion;

/**
 * TACACS+ minor version enumeration
 */
typedef enum tacacs_CTacacsMinorVersion {
    /**
     * TACACS+ Minor Version 0 (Default)
     */
    TACACS_C_TACACS_MINOR_VERSION_TACACS_PLUS_MINOR_VER_DEFAULT = 0,
    /**
     * TACACS+ Minor Version 1
     */
    TACACS_C_TACACS_MINOR_VERSION_TACACS_PLUS_MINOR_VER_ONE = 1,
} tacacs_CTacacsMinorVersion;

/**
 * TACACS+ packet type enumeration
 */
typedef enum tacacs_CTacacsType {
    /**
     * Authentication packet
     */
    TACACS_C_TACACS_TYPE_TAC_PLUS_AUTHENTICATION = 1,
    /**
     * Authorization packet (note: British spelling in protocol)
     */
    TACACS_C_TACACS_TYPE_TAC_PLUS_AUTHORISATION = 2,
    /**
     * Accounting packet
     */
    TACACS_C_TACACS_TYPE_TAC_PLUS_ACCOUNTING = 3,
} tacacs_CTacacsType;

/**
 * Result codes for TACACS FFI operations
 */
typedef enum tacacs_TacacsResult {
    /**
     * Operation completed successfully
     */
    TACACS_TACACS_RESULT_SUCCESS = 0,
    /**
     * Invalid input parameter
     */
    TACACS_TACACS_RESULT_INVALID_INPUT = 1,
    /**
     * Network failure
     */
    TACACS_TACACS_RESULT_NETWORK_FAILURE = 2,
    /**
     * TACACS+ protocol error
     */
    TACACS_TACACS_RESULT_PROTOCOL_ERROR = 3,
    /**
     * Memory allocation failure
     */
    TACACS_TACACS_RESULT_MEMORY_ALLOCATION = 4,
    /**
     * Null pointer error
     */
    TACACS_TACACS_RESULT_NULL_POINTER = 5,
    /**
     * Invalid UTF-8 string
     */
    TACACS_TACACS_RESULT_INVALID_UTF8 = 6,
    /**
     * Buffer too small
     */
    TACACS_TACACS_RESULT_BUFFER_TOO_SMALL = 7,
    /**
     * Invalid header data
     */
    TACACS_TACACS_RESULT_INVALID_HEADER = 8,
    /**
     * Invalid packet data
     */
    TACACS_TACACS_RESULT_INVALID_PACKET = 9,
    /**
     * Unknown error
     */
    TACACS_TACACS_RESULT_UNKNOWN = 255,
} tacacs_TacacsResult;

/**
 * Error information structure
 *
 * Contains an error code and an optional error message.
 * The message is allocated by Rust and must be freed using `tacacs_free_error_message()`.
 */
typedef struct tacacs_TacacsError {
    /**
     * Error code
     */
    enum tacacs_TacacsResult code;
    /**
     * Error message (may be null)
     */
    char *message;
} tacacs_TacacsError;

/**
 * Opaque pointer to a TACACS+ header
 */
typedef tacacs_RustHeader tacacs_TacacsHeader;

/**
 * Opaque pointer to a TACACS+ packet
 */
typedef tacacs_RustPacket tacacs_TacacsPacket;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Free an error message allocated by the library
 *
 * # Safety
 *
 * The message pointer must have been returned by a TACACS FFI function
 * and must not be null. After calling this function, the pointer is invalid.
 */
void tacacs_free_error_message(char *message);

/**
 * Free a TacacsError structure
 *
 * # Safety
 *
 * The error pointer must be valid and must have been allocated by this library.
 */
void tacacs_free_error(struct tacacs_TacacsError *error);

/**
 * Create a new TACACS+ header
 *
 * # Safety
 *
 * Returns a pointer to a newly allocated header that must be freed with `tacacs_header_free()`.
 * Returns null on allocation failure.
 */
tacacs_TacacsHeader *tacacs_header_new(enum tacacs_CTacacsMajorVersion major_version,
                                       enum tacacs_CTacacsMinorVersion minor_version,
                                       enum tacacs_CTacacsType tacacs_type,
                                       uint8_t seq_no,
                                       uint8_t flags,
                                       unsigned int session_id,
                                       unsigned int length,
                                       struct tacacs_TacacsError *error);

/**
 * Parse a TACACS+ header from bytes
 *
 * # Safety
 *
 * The `data` pointer must point to at least `data_len` bytes of valid memory.
 * Returns a pointer to a newly allocated header that must be freed with `tacacs_header_free()`.
 * Returns null on parse failure or allocation failure.
 */
tacacs_TacacsHeader *tacacs_header_from_bytes(const uint8_t *data,
                                              uintptr_t data_len,
                                              struct tacacs_TacacsError *error);

/**
 * Serialize a TACACS+ header to bytes
 *
 * # Safety
 *
 * The `header` pointer must be valid and point to a header created by this library.
 * The `buffer` pointer must point to at least 12 bytes of writable memory.
 * Returns the number of bytes written (always 12 for a valid header), or 0 on error.
 */
uintptr_t tacacs_header_to_bytes(const tacacs_TacacsHeader *header,
                                 uint8_t *buffer,
                                 uintptr_t buffer_len,
                                 struct tacacs_TacacsError *error);

/**
 * Get the session ID from a header
 *
 * # Safety
 *
 * The `header` pointer must be valid and point to a header created by this library.
 * Returns 0 if the pointer is null.
 */
unsigned int tacacs_header_get_session_id(const tacacs_TacacsHeader *header);

/**
 * Get the sequence number from a header
 *
 * # Safety
 *
 * The `header` pointer must be valid and point to a header created by this library.
 * Returns 0 if the pointer is null.
 */
uint8_t tacacs_header_get_seq_no(const tacacs_TacacsHeader *header);

/**
 * Get the length from a header
 *
 * # Safety
 *
 * The `header` pointer must be valid and point to a header created by this library.
 * Returns 0 if the pointer is null.
 */
unsigned int tacacs_header_get_length(const tacacs_TacacsHeader *header);

/**
 * Free a TACACS+ header
 *
 * # Safety
 *
 * The `header` pointer must be valid and must have been allocated by this library.
 * After calling this function, the pointer is invalid.
 */
void tacacs_header_free(tacacs_TacacsHeader *header);

/**
 * Create a new TACACS+ packet from a header and body
 *
 * # Safety
 *
 * - The `header` pointer must be valid and point to a header created by this library
 * - The `body` pointer must point to at least `body_len` bytes of valid memory
 * - Returns a pointer to a newly allocated packet that must be freed with `tacacs_packet_free()`
 * - Returns null on error
 */
tacacs_TacacsPacket *tacacs_packet_new(const tacacs_TacacsHeader *header,
                                       const uint8_t *body,
                                       uintptr_t body_len,
                                       struct tacacs_TacacsError *error);

/**
 * Parse a TACACS+ packet from bytes
 *
 * # Safety
 *
 * - The `data` pointer must point to at least `data_len` bytes of valid memory
 * - Returns a pointer to a newly allocated packet that must be freed with `tacacs_packet_free()`
 * - Returns null on parse failure or allocation failure
 */
tacacs_TacacsPacket *tacacs_packet_from_bytes(const uint8_t *data,
                                              uintptr_t data_len,
                                              struct tacacs_TacacsError *error);

/**
 * Serialize a TACACS+ packet to bytes
 *
 * This function returns the serialized bytes in a newly allocated buffer.
 * The caller must free the buffer using `tacacs_free_bytes()`.
 *
 * # Safety
 *
 * - The `packet` pointer must be valid and point to a packet created by this library
 * - The `out_len` pointer must be valid and will be set to the length of the output buffer
 * - Returns a pointer to the allocated buffer, or null on error
 */
uint8_t *tacacs_packet_to_bytes(const tacacs_TacacsPacket *packet,
                                uintptr_t *out_len,
                                struct tacacs_TacacsError *error);

/**
 * Obfuscate a TACACS+ packet
 *
 * Creates a new obfuscated packet from an unobfuscated packet.
 *
 * # Safety
 *
 * - The `packet` pointer must be valid and point to a packet created by this library
 * - The `key` pointer must point to at least `key_len` bytes of valid memory
 * - Returns a pointer to a newly allocated obfuscated packet, or null if already obfuscated
 * - The returned packet must be freed with `tacacs_packet_free()`
 */
tacacs_TacacsPacket *tacacs_packet_obfuscate(const tacacs_TacacsPacket *packet,
                                             const uint8_t *key,
                                             uintptr_t key_len,
                                             struct tacacs_TacacsError *error);

/**
 * Deobfuscate a TACACS+ packet
 *
 * Creates a new deobfuscated packet from an obfuscated packet.
 *
 * # Safety
 *
 * - The `packet` pointer must be valid and point to a packet created by this library
 * - The `key` pointer must point to at least `key_len` bytes of valid memory
 * - Returns a pointer to a newly allocated deobfuscated packet, or null if already deobfuscated
 * - The returned packet must be freed with `tacacs_packet_free()`
 */
tacacs_TacacsPacket *tacacs_packet_deobfuscate(const tacacs_TacacsPacket *packet,
                                               const uint8_t *key,
                                               uintptr_t key_len,
                                               struct tacacs_TacacsError *error);

/**
 * Free a byte buffer allocated by the library
 *
 * # Safety
 *
 * The buffer pointer must have been returned by a TACACS FFI function.
 * After calling this function, the pointer is invalid.
 */
void tacacs_free_bytes(uint8_t *buffer);

/**
 * Free a TACACS+ packet
 *
 * # Safety
 *
 * The `packet` pointer must be valid and must have been allocated by this library.
 * After calling this function, the pointer is invalid.
 */
void tacacs_packet_free(tacacs_TacacsPacket *packet);

/**
 * Free a string allocated by the library
 *
 * # Safety
 *
 * The string pointer must have been returned by a TACACS FFI function
 * and must not be null. After calling this function, the pointer is invalid.
 */
void tacacs_free_string(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TACACS_H */
