/**
 * TACACS-rs FFI Bindings
 * 
 * C/C++ bindings for the TACACS+ protocol implementation.
 * 
 * This header provides a Foreign Function Interface (FFI) to use
 * the TACACS-rs library from C and C++ applications.
 * 
 * @file tacacs.h
 * @version 0.1.1
 * @license MIT
 */


#ifndef TACACS_H
#define TACACS_H

/* Warning: This file is automatically generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * TACACS+ accounting flags
 */
#define tacacs_TACACS_ACCOUNTING_FLAG_START 2

#define tacacs_TACACS_ACCOUNTING_FLAG_STOP 4

#define tacacs_TACACS_ACCOUNTING_FLAG_WATCHDOG 8

/**
 * TACACS+ flags
 */
#define tacacs_TACACS_FLAG_UNENCRYPTED 1

#define tacacs_TACACS_FLAG_SINGLE_CONNECTION 4

/**
 * TACACS+ accounting status enumeration
 */
typedef enum tacacs_CTacacsAccountingStatus {
    /**
     * Accounting success
     */
    TACACS_C_TACACS_ACCOUNTING_STATUS_TAC_PLUS_ACCT_STATUS_SUCCESS = 1,
    /**
     * Accounting error
     */
    TACACS_C_TACACS_ACCOUNTING_STATUS_TAC_PLUS_ACCT_STATUS_ERROR = 2,
    /**
     * Follow-up required
     */
    TACACS_C_TACACS_ACCOUNTING_STATUS_TAC_PLUS_ACCT_STATUS_FOLLOW = 33,
} tacacs_CTacacsAccountingStatus;

/**
 * TACACS+ authentication method enumeration
 */
typedef enum tacacs_CTacacsAuthenticationMethod {
    /**
     * Not set
     */
    TACACS_C_TACACS_AUTHENTICATION_METHOD_TAC_PLUS_AUTHEN_METHOD_NOT_SET = 0,
    /**
     * None
     */
    TACACS_C_TACACS_AUTHENTICATION_METHOD_TAC_PLUS_AUTHEN_METHOD_NONE = 1,
    /**
     * Kerberos 5
     */
    TACACS_C_TACACS_AUTHENTICATION_METHOD_TAC_PLUS_AUTHEN_METHOD_KRB5 = 2,
    /**
     * Line
     */
    TACACS_C_TACACS_AUTHENTICATION_METHOD_TAC_PLUS_AUTHEN_METHOD_LINE = 3,
    /**
     * Enable
     */
    TACACS_C_TACACS_AUTHENTICATION_METHOD_TAC_PLUS_AUTHEN_METHOD_ENABLE = 4,
    /**
     * Local
     */
    TACACS_C_TACACS_AUTHENTICATION_METHOD_TAC_PLUS_AUTHEN_METHOD_LOCAL = 5,
    /**
     * TACACSPlus
     */
    TACACS_C_TACACS_AUTHENTICATION_METHOD_TAC_PLUS_AUTHEN_METHOD_TACACS_PLUS = 6,
    /**
     * Guest
     */
    TACACS_C_TACACS_AUTHENTICATION_METHOD_TAC_PLUS_AUTHEN_METHOD_GUEST = 8,
    /**
     * RADIUS
     */
    TACACS_C_TACACS_AUTHENTICATION_METHOD_TAC_PLUS_AUTHEN_METHOD_RADIUS = 16,
    /**
     * Kerberos 4
     */
    TACACS_C_TACACS_AUTHENTICATION_METHOD_TAC_PLUS_AUTHEN_METHOD_KRB4 = 17,
    /**
     * RCMD
     */
    TACACS_C_TACACS_AUTHENTICATION_METHOD_TAC_PLUS_AUTHEN_METHOD_RCMD = 32,
} tacacs_CTacacsAuthenticationMethod;

/**
 * TACACS+ authentication service enumeration
 */
typedef enum tacacs_CTacacsAuthenticationService {
    /**
     * None
     */
    TACACS_C_TACACS_AUTHENTICATION_SERVICE_TAC_PLUS_AUTHEN_SVC_NONE = 0,
    /**
     * Login
     */
    TACACS_C_TACACS_AUTHENTICATION_SERVICE_TAC_PLUS_AUTHEN_SVC_LOGIN = 1,
    /**
     * Enable
     */
    TACACS_C_TACACS_AUTHENTICATION_SERVICE_TAC_PLUS_AUTHEN_SVC_ENABLE = 2,
    /**
     * PPP
     */
    TACACS_C_TACACS_AUTHENTICATION_SERVICE_TAC_PLUS_AUTHEN_SVC_PPP = 3,
    /**
     * PT
     */
    TACACS_C_TACACS_AUTHENTICATION_SERVICE_TAC_PLUS_AUTHEN_SVC_PT = 5,
    /**
     * RCMD
     */
    TACACS_C_TACACS_AUTHENTICATION_SERVICE_TAC_PLUS_AUTHEN_SVC_RCMD = 6,
    /**
     * X25
     */
    TACACS_C_TACACS_AUTHENTICATION_SERVICE_TAC_PLUS_AUTHEN_SVC_X25 = 7,
    /**
     * NASI
     */
    TACACS_C_TACACS_AUTHENTICATION_SERVICE_TAC_PLUS_AUTHEN_SVC_NASI = 8,
    /**
     * FWProxy
     */
    TACACS_C_TACACS_AUTHENTICATION_SERVICE_TAC_PLUS_AUTHEN_SVC_FWPROXY = 9,
} tacacs_CTacacsAuthenticationService;

/**
 * TACACS+ authentication type enumeration
 */
typedef enum tacacs_CTacacsAuthenticationType {
    /**
     * Not set
     */
    TACACS_C_TACACS_AUTHENTICATION_TYPE_TAC_PLUS_AUTHEN_TYPE_NOT_SET = 0,
    /**
     * ASCII
     */
    TACACS_C_TACACS_AUTHENTICATION_TYPE_TAC_PLUS_AUTHEN_TYPE_ASCII = 1,
    /**
     * PAP
     */
    TACACS_C_TACACS_AUTHENTICATION_TYPE_TAC_PLUS_AUTHEN_TYPE_PAP = 2,
    /**
     * CHAP
     */
    TACACS_C_TACACS_AUTHENTICATION_TYPE_TAC_PLUS_AUTHEN_TYPE_CHAP = 3,
    /**
     * MSCHAP
     */
    TACACS_C_TACACS_AUTHENTICATION_TYPE_TAC_PLUS_AUTHEN_TYPE_MSCHAP = 5,
    /**
     * MSCHAPv2
     */
    TACACS_C_TACACS_AUTHENTICATION_TYPE_TAC_PLUS_AUTHEN_TYPE_MSCHAPV2 = 6,
} tacacs_CTacacsAuthenticationType;

/**
 * TACACS+ major version enumeration
 */
typedef enum tacacs_CTacacsMajorVersion {
    /**
     * TACACS+ Major Version 1 (0xC)
     */
    TACACS_C_TACACS_MAJOR_VERSION_TACACS_PLUS_MAJOR1 = 12,
} tacacs_CTacacsMajorVersion;

/**
 * TACACS+ minor version enumeration
 */
typedef enum tacacs_CTacacsMinorVersion {
    /**
     * TACACS+ Minor Version 0 (Default)
     */
    TACACS_C_TACACS_MINOR_VERSION_TACACS_PLUS_MINOR_VER_DEFAULT = 0,
    /**
     * TACACS+ Minor Version 1
     */
    TACACS_C_TACACS_MINOR_VERSION_TACACS_PLUS_MINOR_VER_ONE = 1,
} tacacs_CTacacsMinorVersion;

/**
 * TACACS+ packet type enumeration
 */
typedef enum tacacs_CTacacsType {
    /**
     * Authentication packet
     */
    TACACS_C_TACACS_TYPE_TAC_PLUS_AUTHENTICATION = 1,
    /**
     * Authorization packet (note: British spelling in protocol)
     */
    TACACS_C_TACACS_TYPE_TAC_PLUS_AUTHORISATION = 2,
    /**
     * Accounting packet
     */
    TACACS_C_TACACS_TYPE_TAC_PLUS_ACCOUNTING = 3,
} tacacs_CTacacsType;

/**
 * Result codes for TACACS FFI operations
 */
typedef enum tacacs_TacacsResult {
    /**
     * Operation completed successfully
     */
    TACACS_TACACS_RESULT_SUCCESS = 0,
    /**
     * Invalid input parameter
     */
    TACACS_TACACS_RESULT_INVALID_INPUT = 1,
    /**
     * Network failure
     */
    TACACS_TACACS_RESULT_NETWORK_FAILURE = 2,
    /**
     * TACACS+ protocol error
     */
    TACACS_TACACS_RESULT_PROTOCOL_ERROR = 3,
    /**
     * Memory allocation failure
     */
    TACACS_TACACS_RESULT_MEMORY_ALLOCATION = 4,
    /**
     * Null pointer error
     */
    TACACS_TACACS_RESULT_NULL_POINTER = 5,
    /**
     * Invalid UTF-8 string
     */
    TACACS_TACACS_RESULT_INVALID_UTF8 = 6,
    /**
     * Buffer too small
     */
    TACACS_TACACS_RESULT_BUFFER_TOO_SMALL = 7,
    /**
     * Invalid header data
     */
    TACACS_TACACS_RESULT_INVALID_HEADER = 8,
    /**
     * Invalid packet data
     */
    TACACS_TACACS_RESULT_INVALID_PACKET = 9,
    /**
     * Unknown error
     */
    TACACS_TACACS_RESULT_UNKNOWN = 255,
} tacacs_TacacsResult;

/**
 * Opaque type for TACACS+ accounting request
 */
typedef struct tacacs_TacacsAccountingRequest {
    uint8_t private_[0];
} tacacs_TacacsAccountingRequest;

/**
 * Error information structure
 *
 * Contains an error code and an optional error message.
 * The message is allocated by Rust and must be freed using `tacacs_free_error_message()`.
 */
typedef struct tacacs_TacacsError {
    /**
     * Error code
     */
    enum tacacs_TacacsResult code;
    /**
     * Error message (may be null)
     */
    char *message;
} tacacs_TacacsError;

/**
 * Opaque type for TACACS+ packet
 */
typedef struct tacacs_TacacsPacket {
    uint8_t private_[0];
} tacacs_TacacsPacket;

/**
 * Opaque type for TACACS+ accounting reply
 */
typedef struct tacacs_TacacsAccountingReply {
    uint8_t private_[0];
} tacacs_TacacsAccountingReply;

/**
 * Opaque type for TACACS+ header
 */
typedef struct tacacs_TacacsHeader {
    uint8_t private_[0];
} tacacs_TacacsHeader;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new TACACS+ accounting request
 *
 * # Safety
 *
 * - All string pointers must be valid null-terminated UTF-8 strings
 * - The `args` array must contain `args_count` valid string pointers
 * - Returns a pointer to a newly allocated request that must be freed with `tacacs_accounting_request_free()`
 * - Returns null on error
 */
struct tacacs_TacacsAccountingRequest *tacacs_accounting_request_new(uint8_t flags,
                                                                     enum tacacs_CTacacsAuthenticationMethod authen_method,
                                                                     uint8_t priv_lvl,
                                                                     enum tacacs_CTacacsAuthenticationType authen_type,
                                                                     enum tacacs_CTacacsAuthenticationService authen_service,
                                                                     const char *user,
                                                                     const char *port,
                                                                     const char *rem_address,
                                                                     const char *const *args,
                                                                     uintptr_t args_count,
                                                                     struct tacacs_TacacsError *error);

/**
 * Parse a TACACS+ accounting request from a packet
 *
 * # Safety
 *
 * - The `packet` pointer must be valid and point to a packet created by this library
 * - Returns a pointer to a newly allocated request that must be freed with `tacacs_accounting_request_free()`
 * - Returns null on parse failure or allocation failure
 */
struct tacacs_TacacsAccountingRequest *tacacs_accounting_request_from_packet(const struct tacacs_TacacsPacket *packet,
                                                                             struct tacacs_TacacsError *error);

/**
 * Convert a TACACS+ accounting request to bytes
 *
 * # Safety
 *
 * - The `request` pointer must be valid and point to a request created by this library
 * - Returns a pointer to an allocated byte buffer, or null on error
 * - The returned buffer must be freed with `tacacs_free_bytes()`
 */
uint8_t *tacacs_accounting_request_to_bytes(const struct tacacs_TacacsAccountingRequest *request,
                                            uintptr_t *out_len,
                                            struct tacacs_TacacsError *error);

/**
 * Get the user field from an accounting request
 *
 * # Safety
 *
 * - The `request` pointer must be valid and point to a request created by this library
 * - Returns an allocated string that must be freed with `tacacs_free_string()`
 * - Returns null if the pointer is null
 */
char *tacacs_accounting_request_get_user(const struct tacacs_TacacsAccountingRequest *request);

/**
 * Get the port field from an accounting request
 *
 * # Safety
 *
 * - The `request` pointer must be valid and point to a request created by this library
 * - Returns an allocated string that must be freed with `tacacs_free_string()`
 * - Returns null if the pointer is null
 */
char *tacacs_accounting_request_get_port(const struct tacacs_TacacsAccountingRequest *request);

/**
 * Get the remote address field from an accounting request
 *
 * # Safety
 *
 * - The `request` pointer must be valid and point to a request created by this library
 * - Returns an allocated string that must be freed with `tacacs_free_string()`
 * - Returns null if the pointer is null
 */
char *tacacs_accounting_request_get_rem_address(const struct tacacs_TacacsAccountingRequest *request);

/**
 * Get the privilege level from an accounting request
 *
 * # Safety
 *
 * - The `request` pointer must be valid and point to a request created by this library
 * - Returns 0 if the pointer is null
 */
uint8_t tacacs_accounting_request_get_priv_lvl(const struct tacacs_TacacsAccountingRequest *request);

/**
 * Get the flags from an accounting request
 *
 * # Safety
 *
 * - The `request` pointer must be valid and point to a request created by this library
 * - Returns 0 if the pointer is null
 */
uint8_t tacacs_accounting_request_get_flags(const struct tacacs_TacacsAccountingRequest *request);

/**
 * Free a TACACS+ accounting request
 *
 * # Safety
 *
 * - The `request` pointer must be valid and must have been allocated by this library
 * - After calling this function, the pointer is invalid
 */
void tacacs_accounting_request_free(struct tacacs_TacacsAccountingRequest *request);

/**
 * Create a new TACACS+ accounting reply
 *
 * # Safety
 *
 * - All string pointers must be valid null-terminated UTF-8 strings
 * - Returns a pointer to a newly allocated reply that must be freed with `tacacs_accounting_reply_free()`
 * - Returns null on error
 */
struct tacacs_TacacsAccountingReply *tacacs_accounting_reply_new(enum tacacs_CTacacsAccountingStatus status,
                                                                 const char *server_msg,
                                                                 const char *data,
                                                                 struct tacacs_TacacsError *error);

/**
 * Parse a TACACS+ accounting reply from a packet
 *
 * # Safety
 *
 * - The `packet` pointer must be valid and point to a packet created by this library
 * - Returns a pointer to a newly allocated reply that must be freed with `tacacs_accounting_reply_free()`
 * - Returns null on parse failure or allocation failure
 */
struct tacacs_TacacsAccountingReply *tacacs_accounting_reply_from_packet(const struct tacacs_TacacsPacket *packet,
                                                                         struct tacacs_TacacsError *error);

/**
 * Convert a TACACS+ accounting reply to bytes
 *
 * # Safety
 *
 * - The `reply` pointer must be valid and point to a reply created by this library
 * - Returns a pointer to an allocated byte buffer, or null on error
 * - The returned buffer must be freed with `tacacs_free_bytes()`
 */
uint8_t *tacacs_accounting_reply_to_bytes(const struct tacacs_TacacsAccountingReply *reply,
                                          uintptr_t *out_len,
                                          struct tacacs_TacacsError *error);

/**
 * Get the server message from an accounting reply
 *
 * # Safety
 *
 * - The `reply` pointer must be valid and point to a reply created by this library
 * - Returns an allocated string that must be freed with `tacacs_free_string()`
 * - Returns null if the pointer is null
 */
char *tacacs_accounting_reply_get_server_msg(const struct tacacs_TacacsAccountingReply *reply);

/**
 * Get the data field from an accounting reply
 *
 * # Safety
 *
 * - The `reply` pointer must be valid and point to a reply created by this library
 * - Returns an allocated string that must be freed with `tacacs_free_string()`
 * - Returns null if the pointer is null
 */
char *tacacs_accounting_reply_get_data(const struct tacacs_TacacsAccountingReply *reply);

/**
 * Get the status from an accounting reply
 *
 * # Safety
 *
 * - The `reply` pointer must be valid and point to a reply created by this library
 * - Returns the status code, or TacPlusAcctStatusError if the pointer is null
 */
enum tacacs_CTacacsAccountingStatus tacacs_accounting_reply_get_status(const struct tacacs_TacacsAccountingReply *reply);

/**
 * Free a TACACS+ accounting reply
 *
 * # Safety
 *
 * - The `reply` pointer must be valid and must have been allocated by this library
 * - After calling this function, the pointer is invalid
 */
void tacacs_accounting_reply_free(struct tacacs_TacacsAccountingReply *reply);

/**
 * Free an error message allocated by the library
 *
 * # Safety
 *
 * The message pointer must have been returned by a TACACS FFI function
 * and must not be null. After calling this function, the pointer is invalid.
 */
void tacacs_free_error_message(char *message);

/**
 * Free a TacacsError structure
 *
 * # Safety
 *
 * The error pointer must be valid and must have been allocated by this library.
 */
void tacacs_free_error(struct tacacs_TacacsError *error);

/**
 * Create a new TACACS+ header
 *
 * # Safety
 *
 * Returns a pointer to a newly allocated header that must be freed with `tacacs_header_free()`.
 * Returns null on allocation failure.
 */
struct tacacs_TacacsHeader *tacacs_header_new(enum tacacs_CTacacsMajorVersion major_version,
                                              enum tacacs_CTacacsMinorVersion minor_version,
                                              enum tacacs_CTacacsType tacacs_type,
                                              uint8_t seq_no,
                                              uint8_t flags,
                                              unsigned int session_id,
                                              unsigned int length,
                                              struct tacacs_TacacsError *error);

/**
 * Parse a TACACS+ header from bytes
 *
 * # Safety
 *
 * The `data` pointer must point to at least `data_len` bytes of valid memory.
 * Returns a pointer to a newly allocated header that must be freed with `tacacs_header_free()`.
 * Returns null on parse failure or allocation failure.
 */
struct tacacs_TacacsHeader *tacacs_header_from_bytes(const uint8_t *data,
                                                     uintptr_t data_len,
                                                     struct tacacs_TacacsError *error);

/**
 * Serialize a TACACS+ header to bytes
 *
 * # Safety
 *
 * The `header` pointer must be valid and point to a header created by this library.
 * The `buffer` pointer must point to at least 12 bytes of writable memory.
 * Returns the number of bytes written (always 12 for a valid header), or 0 on error.
 */
uintptr_t tacacs_header_to_bytes(const struct tacacs_TacacsHeader *header,
                                 uint8_t *buffer,
                                 uintptr_t buffer_len,
                                 struct tacacs_TacacsError *error);

/**
 * Get the session ID from a header
 *
 * # Safety
 *
 * The `header` pointer must be valid and point to a header created by this library.
 * Returns 0 if the pointer is null.
 */
unsigned int tacacs_header_get_session_id(const struct tacacs_TacacsHeader *header);

/**
 * Get the sequence number from a header
 *
 * # Safety
 *
 * The `header` pointer must be valid and point to a header created by this library.
 * Returns 0 if the pointer is null.
 */
uint8_t tacacs_header_get_seq_no(const struct tacacs_TacacsHeader *header);

/**
 * Get the length from a header
 *
 * # Safety
 *
 * The `header` pointer must be valid and point to a header created by this library.
 * Returns 0 if the pointer is null.
 */
unsigned int tacacs_header_get_length(const struct tacacs_TacacsHeader *header);

/**
 * Free a TACACS+ header
 *
 * # Safety
 *
 * The `header` pointer must be valid and must have been allocated by this library.
 * After calling this function, the pointer is invalid.
 */
void tacacs_header_free(struct tacacs_TacacsHeader *header);

/**
 * Create a new TACACS+ packet from a header and body
 *
 * # Safety
 *
 * - The `header` pointer must be valid and point to a header created by this library
 * - The `body` pointer must point to at least `body_len` bytes of valid memory
 * - Returns a pointer to a newly allocated packet that must be freed with `tacacs_packet_free()`
 * - Returns null on error
 */
struct tacacs_TacacsPacket *tacacs_packet_new(const struct tacacs_TacacsHeader *header,
                                              const uint8_t *body,
                                              uintptr_t body_len,
                                              struct tacacs_TacacsError *error);

/**
 * Parse a TACACS+ packet from bytes
 *
 * # Safety
 *
 * - The `data` pointer must point to at least `data_len` bytes of valid memory
 * - Returns a pointer to a newly allocated packet that must be freed with `tacacs_packet_free()`
 * - Returns null on parse failure or allocation failure
 */
struct tacacs_TacacsPacket *tacacs_packet_from_bytes(const uint8_t *data,
                                                     uintptr_t data_len,
                                                     struct tacacs_TacacsError *error);

/**
 * Serialize a TACACS+ packet to bytes
 *
 * This function returns the serialized bytes in a newly allocated buffer.
 * The caller must free the buffer using `tacacs_free_bytes()`.
 *
 * # Safety
 *
 * - The `packet` pointer must be valid and point to a packet created by this library
 * - The `out_len` pointer must be valid and will be set to the length of the output buffer
 * - Returns a pointer to the allocated buffer, or null on error
 */
uint8_t *tacacs_packet_to_bytes(const struct tacacs_TacacsPacket *packet,
                                uintptr_t *out_len,
                                struct tacacs_TacacsError *error);

/**
 * Obfuscate a TACACS+ packet
 *
 * Creates a new obfuscated packet from an unobfuscated packet.
 *
 * # Safety
 *
 * - The `packet` pointer must be valid and point to a packet created by this library
 * - The `key` pointer must point to at least `key_len` bytes of valid memory
 * - Returns a pointer to a newly allocated obfuscated packet, or null if already obfuscated
 * - The returned packet must be freed with `tacacs_packet_free()`
 */
struct tacacs_TacacsPacket *tacacs_packet_obfuscate(const struct tacacs_TacacsPacket *packet,
                                                    const uint8_t *key,
                                                    uintptr_t key_len,
                                                    struct tacacs_TacacsError *error);

/**
 * Deobfuscate a TACACS+ packet
 *
 * Creates a new deobfuscated packet from an obfuscated packet.
 *
 * # Safety
 *
 * - The `packet` pointer must be valid and point to a packet created by this library
 * - The `key` pointer must point to at least `key_len` bytes of valid memory
 * - Returns a pointer to a newly allocated deobfuscated packet, or null if already deobfuscated
 * - The returned packet must be freed with `tacacs_packet_free()`
 */
struct tacacs_TacacsPacket *tacacs_packet_deobfuscate(const struct tacacs_TacacsPacket *packet,
                                                      const uint8_t *key,
                                                      uintptr_t key_len,
                                                      struct tacacs_TacacsError *error);

/**
 * Free a byte buffer allocated by the library
 *
 * # Safety
 *
 * The buffer pointer must have been returned by a TACACS FFI function.
 * After calling this function, the pointer is invalid.
 */
void tacacs_free_bytes(uint8_t *buffer);

/**
 * Free a TACACS+ packet
 *
 * # Safety
 *
 * The `packet` pointer must be valid and must have been allocated by this library.
 * After calling this function, the pointer is invalid.
 */
void tacacs_packet_free(struct tacacs_TacacsPacket *packet);

/**
 * Free a string allocated by the library
 *
 * # Safety
 *
 * The string pointer must have been returned by a TACACS FFI function
 * and must not be null. After calling this function, the pointer is invalid.
 */
void tacacs_free_string(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TACACS_H */
