name: Make Sure That Dependencies Are Used
description: Run cargo-udeps for a target platform

inputs:
  package-args:
    description: 'Cargo workspace or package selection arguments'
    required: false
    default: '--workspace'
  target:
    description: 'Rust target triple for the validation'
    required: true
  feature-args:
    description: 'Cargo feature arguments to append'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install cargo-udeps
      uses: taiki-e/install-action@7be9fd86bd1707236395105d6e9329dd1511a7e1 # v2.79.0
      with:
        tool: cargo-udeps

    - name: Run cargo-udeps
      shell: bash
      run: |
        cargo +nightly udeps \
          ${{ inputs.package-args }} \
          --all-targets \
          --target "${{ inputs.target }}" \
          ${{ inputs.feature-args }}
