name: Check Unused Dependencies
description: Run cargo-udeps for a target platform

inputs:
  target:
    description: 'Rust target triple to check'
    required: true
  feature-args:
    description: 'Cargo feature arguments to append'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install cargo-udeps
      uses: taiki-e/install-action@7be9fd86bd1707236395105d6e9329dd1511a7e1 # v2.79.0
      with:
        tool: cargo-udeps

    - name: Check unused dependencies
      shell: bash
      run: |
        cargo +nightly udeps \
          --workspace \
          --all-targets \
          --target "${{ inputs.target }}" \
          ${{ inputs.feature-args }}
