#!/bin/sh
set -e

CONFIG_FILE=/etc/bash_plugins.conf
START_MARKER="# tacacsrs-bash-plugin managed block start"
END_MARKER="# tacacsrs-bash-plugin managed block end"

remove_managed_block() {
    file="$1"

    if [ -f "$file" ]; then
        sed -i "/^${START_MARKER}$/,/^${END_MARKER}$/d" "$file"
    fi
}

case "$1" in
    remove|purge)
        remove_managed_block "$CONFIG_FILE"
        ;;
esac

if [ "$1" = "purge" ]; then
    . /usr/share/debconf/confmodule
    db_purge || true
    db_stop || true
fi

exit 0