[package]
name = "tacon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.89", features = ["backtrace"] }
byteorder = "1.5.0"
clap = { version = "4.5.17", features = ["derive"] }
tacacsrs-messages = { path = "../../libraries/tacacsrs_messages" }

