[package]
name = "tacacsrs-agent-ipc-emulator"
version = "0.0.0-dev"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A local IPC emulator that uses Rego for TACACS+ agent integration tests."
readme = "README.md"
build = "build.rs"

[dependencies]
anyhow = { version = "1.0.102", features = ["backtrace"] }
http = "1.4.1"
hyper-util = "0.1.20"
log = "0.4"
prost = "0.14.3"
regorus = { version = "0.11.0", default-features = false, features = ["arc", "regex"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tacacsrs-agent-client = { path = "../tacacsrs_agent_client" }
tokio = { version = "1.52.2", features = ["full"] }
tokio-stream = { version = "0.1.18", features = ["net"] }
tonic = "0.14.6"
tonic-prost = "0.14.6"
tower = { version = "0.5.3", features = ["util"] }

[build-dependencies]
protoc-bin-vendored = "3.2.0"
tonic-prost-build = "0.14.6"

[dev-dependencies]
tempfile = "3.27.0"

[lints]
workspace = true
