name: Make Sure That Formatting Is Correct
description: Run rustfmt over the Rust workspace

runs:
  using: composite
  steps:
    - name: Run rustfmt
      shell: bash
      run: cargo +nightly fmt --all -- --check
