name: Run Clippy
description: Run clippy for a target platform

inputs:
  package-args:
    description: 'Cargo workspace or package selection arguments'
    required: false
    default: '--workspace'
  target:
    description: 'Rust target triple to lint'
    required: true
  feature-args:
    description: 'Cargo feature arguments to append'
    required: false
    default: ''
  lint-args:
    description: 'Arguments passed after cargo clippy --'
    required: false
    default: '-D warnings'
  advisory:
    description: 'Report Clippy errors as warnings. Do not stop the workflow.'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Run Clippy
      shell: bash
      run: |
        if [ "${{ inputs.advisory }}" = "true" ]; then
          cargo clippy \
            ${{ inputs.package-args }} \
            --all-targets \
            --target "${{ inputs.target }}" \
            ${{ inputs.feature-args }} \
            -- ${{ inputs.lint-args }} || \
            echo "::warning::Clippy found errors during advisory validation."
        else
          cargo clippy \
            ${{ inputs.package-args }} \
            --all-targets \
            --target "${{ inputs.target }}" \
            ${{ inputs.feature-args }} \
            -- ${{ inputs.lint-args }}
        fi
