services:
  tacplus:
    build: https://github.com/christian-becker/tac_plus-ng.git#main
    image: 'tac_plus:ubuntu'
    restart: unless-stopped
    command: ["/usr/local/sbin/tac_plus-ng", "/usr/local/etc/tac_plus.cfg"]
    environment:
      - TZ=Australia/Brisbane
    ports:
      - '4949:4949'
      - '4449:4449'
      - '4450:4450'
    volumes:
      - ./config:/usr/local/etc/