name: Reusable Unused Dependencies

on:
  workflow_call:

permissions:
  contents: read

jobs:
  unused-deps:
    name: Unused Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Rust
        uses: ./.github/steps/setup-rust
        with:
          toolchain: nightly
          cache-key: nightly

      - name: Install cargo-udeps
        uses: taiki-e/install-action@eea29cff9a2b68892c0845ae3e4f45fc47ee9354 # v2.75.13
        with:
          tool: cargo-udeps

      - name: Check for unused dependencies
        run: cargo +nightly udeps --workspace --all-targets
