name: Reusable Miri

on:
  workflow_call:
    inputs:
      continue-on-error:
        description: 'Whether to allow this check to fail without failing the workflow'
        required: false
        default: true
        type: boolean

jobs:
  miri:
    name: Miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Rust
        uses: ./.github/steps/setup-rust
        with:
          toolchain: nightly
          components: miri
          cache-key: nightly

      - name: Run Miri
        run: cargo +nightly miri test --workspace --all-features
        continue-on-error: ${{ inputs.continue-on-error }}
        env:
          MIRIFLAGS: -Zmiri-disable-isolation
