name: Reusable Clippy Nursery

on:
  workflow_call:
    inputs:
      continue-on-error:
        description: 'Whether to allow this check to fail without failing the workflow'
        required: false
        default: true
        type: boolean

jobs:
  clippy-nursery:
    name: Clippy Nursery
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Rust
        uses: ./.github/steps/setup-rust
        with:
          components: clippy
          cache-key: stable

      - name: Clippy nursery lints
        run: cargo clippy --workspace --all-targets --all-features -- -W clippy::nursery
        continue-on-error: ${{ inputs.continue-on-error }}
