name: Reusable Outdated Dependencies

on:
  workflow_call:

permissions:
  contents: read

jobs:
  outdated:
    name: Outdated Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Rust
        uses: ./.github/steps/setup-rust
        with:
          cache-key: stable

      - name: Install cargo-outdated
        uses: taiki-e/install-action@fa0dd4cd0a40696e6f9766370614a5ce482e6aa8 # v2.77.5
        with:
          tool: cargo-outdated

      - name: Check for outdated dependencies
        run: cargo outdated --workspace --exit-code 1
